// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WhatDayPCL.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WhatDayPCL.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About_ReleaseDate {
            get {
                return ResourceManager.GetString("About_ReleaseDate", resourceCulture);
            }
        }
        
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        internal static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        internal static string Settings_DatesSectionTitle {
            get {
                return ResourceManager.GetString("Settings_DatesSectionTitle", resourceCulture);
            }
        }
        
        internal static string Common_AboutButtonLabel {
            get {
                return ResourceManager.GetString("Common_AboutButtonLabel", resourceCulture);
            }
        }
        
        internal static string Common_SettingsButtonLabel {
            get {
                return ResourceManager.GetString("Common_SettingsButtonLabel", resourceCulture);
            }
        }
        
        internal static string About_Details {
            get {
                return ResourceManager.GetString("About_Details", resourceCulture);
            }
        }
        
        internal static string DayCountFormat {
            get {
                return ResourceManager.GetString("DayCountFormat", resourceCulture);
            }
        }
        
        internal static string Home_PageTitle {
            get {
                return ResourceManager.GetString("Home_PageTitle", resourceCulture);
            }
        }
        
        internal static string About_Language {
            get {
                return ResourceManager.GetString("About_Language", resourceCulture);
            }
        }
        
        internal static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        internal static string Settings_StartDateInputLabel {
            get {
                return ResourceManager.GetString("Settings_StartDateInputLabel", resourceCulture);
            }
        }
    }
}
